FROM golang:1.25-alpine AS builder
RUN apk add --no-cache git ca-certificates && \
    go install github.com/air-verse/air@latest

FROM golang:1.25-alpine
RUN apk add --no-cache ca-certificates git

COPY --from=builder /go/bin/air /usr/local/bin/air

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOCACHE=/root/.cache/go-build

WORKDIR /app

EXPOSE 8080

CMD ["air"]
